// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIZpXz7B0VdAHsf3040WkgjtGJNEYDdc8',
    appId: '1:287341469356:web:32ac70dddb66ddbf230909',
    messagingSenderId: '287341469356',
    projectId: 'moviebookingapp-7324a',
    authDomain: 'moviebookingapp-7324a.firebaseapp.com',
    storageBucket: 'moviebookingapp-7324a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIupww2qLxoDlTd5Ir4PDVUTdC4RqpZN4',
    appId: '1:287341469356:android:82f802b73fc85bec230909',
    messagingSenderId: '287341469356',
    projectId: 'moviebookingapp-7324a',
    storageBucket: 'moviebookingapp-7324a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKhdVOZlHMFzutoKxARlcjAIq5SsimIa0',
    appId: '1:287341469356:ios:8305cc348796885b230909',
    messagingSenderId: '287341469356',
    projectId: 'moviebookingapp-7324a',
    storageBucket: 'moviebookingapp-7324a.appspot.com',
    iosBundleId: 'com.example.movieBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKhdVOZlHMFzutoKxARlcjAIq5SsimIa0',
    appId: '1:287341469356:ios:8f75071531ecb741230909',
    messagingSenderId: '287341469356',
    projectId: 'moviebookingapp-7324a',
    storageBucket: 'moviebookingapp-7324a.appspot.com',
    iosBundleId: 'com.example.movieBookingApp.RunnerTests',
  );
}
